import Head from 'next/head'
// import Image from 'next/image'
import { useRef } from 'react';
import { Inter } from 'next/font/google'


// import styles from '@/styles/Home.module.css'


import About from "../components/About";
import Work from "../components/Work";
import Hero from "../components/Hero";
import Layout from "../components/Layout/Layout";
import Skills from '@/components/Skills';
import Services from './Services';
import Method from './Method';
import Consult from './Consult';


// import SeoHead from "../components/SeoHead";

const inter = Inter({ subsets: ['latin'] })



export default function Home() {
 
  return (
    <>
      <Head>
        <title>CMStudios</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/assets/astro2float-removebg-preview.png" />
      </Head>
      {/* <SeoHead title='LaslesVPN Landing Page' /> */}
      <div className="parent scrollbar-hide">
      <Layout>
       
        <Hero/>
     
        <Skills/>
       
       
        <About />
        <Work />
     
        {/* <Services/>
        <Method/>
        <Consult/> */}
      </Layout>
      </div>
      </>
  )
}
